"""empty message

Revision ID: 84797d689c13
Revises: 5bef6936e04c
Create Date: 2022-11-13 17:19:13.114905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84797d689c13'
down_revision = '5bef6936e04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.add_column('users', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'wallets', ['wallet_id'], ['id'])
    op.alter_column('wallets', 'balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'balance',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'wallet_id')
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
