"""empty message

Revision ID: 865ed3bb7531
Revises: 
Create Date: 2022-10-29 14:07:53.503970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865ed3bb7531'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'resources', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
