"""empty message

Revision ID: 9176e165477d
Revises: 178a951dcea5
Create Date: 2022-11-11 22:02:29.266982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9176e165477d'
down_revision = '178a951dcea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_transaction_id', table_name='categories')
    op.drop_constraint('categories_transaction_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'transaction_id')
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=False))
    op.alter_column('transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('transactions', 'category_id')
    op.add_column('categories', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('categories_transaction_id_fkey', 'categories', 'transactions', ['transaction_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_categories_transaction_id', 'categories', ['transaction_id'], unique=False)
    # ### end Alembic commands ###
